DROP TABLE USR;
Create Table USR
(
   ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
   NAME VARCHAR(100) NOT NULL,
   EMAIL VARCHAR(50) NOT NULL,
   PWDHASH VARCHAR(50) NOT NULL,
   PRIMARY KEY(ID),
   CONSTRAINT UNQ_USR_EMAIL UNIQUE(EMAIL)
);

DROP TABLE CODE_SET;
CREATE TABLE CODE_SET
(
   NAME VARCHAR(10) NOT NULL,
   CODE VARCHAR(10) NOT NULL,
   CD_DESC VARCHAR(1000) NOT NULL,
   USER_ID INT UNSIGNED NOT NULL,
   PRIMARY KEY(NAME,CODE),
   CONSTRAINT FK_CD_USR FOREIGN KEY(USER_ID) REFERENCES USR(ID)
);

DROP TABLE DISH;
Create Table DISH
(
   ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
   DISH_NM VARCHAR(10) NOT NULL,
   CUSN_CD VARCHAR(10) NOT NULL,
   USER_ID INT UNSIGNED NOT NULL,
   PRIMARY KEY(ID),
   CONSTRAINT FK_DISH_USR FOREIGN KEY(USER_ID) REFERENCES USR(ID)

);


DROP TABLE MENU;
Create Table MENU
(
   ID  INT UNSIGNED NOT NULL AUTO_INCREMENT,
   DT DATE NOT NULL,
   MEAL_CD VARCHAR(10) NOT NULL,
   DISH_ID INT UNSIGNED NOT NULL,
   USER_ID INT UNSIGNED NOT NULL,
   PRIMARY KEY(ID),
   CONSTRAINT FK_MENU_DISH FOREIGN KEY(DISH_ID) REFERENCES DISH(ID),
   CONSTRAINT FK_MENU_USR FOREIGN KEY(USER_ID) REFERENCES USR(ID)

);

DROP TABLE RCP_ING
Create Table RCP_ING
(
   DISH_ID INT UNSIGNED NOT NULL,
   ING_CD  VARCHAR(10) NOT NULL ,
   PRIMARY KEY(DISH_ID,ING_CD),
   CONSTRAINT FK_ING_DISH FOREIGN KEY(DISH_ID) REFERENCES DISH(ID)
);

DROP TABLE RCP_STEPS;
CREATE TABLE RCP_STEPS
(
   ID  INT UNSIGNED NOT NULL AUTO_INCREMENT,
   DISH_ID INT UNSIGNED,
   STEPS   VARCHAR(1000) NOT NULL,
   PRIMARY KEY(ID),
   CONSTRAINT FK_STP_DISH FOREIGN KEY(DISH_ID) REFERENCES DISH(ID)
);

